default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DEBUG: false
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .static
  DIRS_RESOURCES:
    - config
    - src/applications/hello/static
    - src/project/static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/applications/hello/templates
    - src/applications/home/templates
    - src/project/templates
  GUNICORN_TIMEOUT: 30
  PROJECT_NAME: ""
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false


development:
  DEBUG: true
  GUNICORN_TIMEOUT: 300
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 1


heroku:
  ALLOWED_HOSTS:
    - "tms-z33.herokuapp.com"
  VENV_SYNTHETIC: true


ci:
  DATABASE_URL: "postgres://ci:ci@localhost:5432/ci?sslmode=disable"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2